In [70]:
import numpy as np
import pandas as pd
from sklearn.impute import KNNImputer
from tensorflow import keras
from tensorflow.keras import layers
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt
from tensorflow.keras.callbacks import EarlyStopping

In [71]:
data=pd.read_csv('/kaggle/input/datasets/emadhamdy11111/berest-cancer-data/breast_cancer_dirty.csv')

data.head()

,id,Diagnosis,Radius_Mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,SMOOTHNESS_WORST,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,902727,B,13.28,13.72,85.79,541.8,0.08363,0.08575,0.05077,0.02864,...,17.37,96.59,623.7,0.1166,0.2685,0.2866,0.09173,0.2736,0.07320,NaN
1,8711002,B,13.15,15.34,85.31,538.9,0.09384,0.08498,0.09293,0.03483,...,20.50,97.67,677.3,0.1478,0.2256,0.3009,0.09722,0.3849,0.08633,NaN
2,9012568,b,15.19,13.21,97.65,711.8,0.07963,0.06934,NaN,0.02657,...,15.73,104.50,819.1,0.1126,0.1737,0.1362,0.08178,0.2487,0.06766,NaN
3,864018,b,11.34,21.26,72.48,396.5,0.08759,0.06575,0.05133,0.01899,...,29.15,83.99,518.1,0.1699,0.2196,0.3120,0.08278,0.2829,0.08832,NaN
4,892604,B,12.46,19.89,80.43,471.3,0.08451,0.10140,0.06830,0.03099,...,23.07,88.13,551.3,0.1050,0.2158,0.1904,0.07625,0.2685,0.07764,NaN

In [72]:
data.shape

(587, 33)

In [73]:
data.isna().sum()

id                           0
Diagnosis                    4
Radius_Mean                  0
 texture_mean               12
perimeter_mean               7
area_mean                    0
smoothness_mean              9
compactness_mean             0
concavity_mean              10
concave points_mean          0
symmetry_mean                0
fractal_dimension_mean       0
radius_se                    0
texture_se                   0
perimeter_se                 0
area_se                      0
smoothness_se                0
compactness_se               0
concavity_se                 0
concave points_se            0
symmetry_se                  0
fractal_dimension_se         0
radius_worst                 0
texture_worst                0
perimeter_worst              0
area_worst                   0
SMOOTHNESS_WORST             0
compactness_worst            0
concavity_worst              0
concave points_worst         0
symmetry_worst              15
fractal_dimension_worst      0
Unnamed: 32                587
dtype: int64

In [74]:
data.dtypes

id                           int64
Diagnosis                   object
Radius_Mean                float64
 texture_mean              float64
perimeter_mean             float64
area_mean                   object
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
SMOOTHNESS_WORST           float64
compactness_worst          float64
concavity_worst            float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
Unnamed: 32                float64
dtype: object

In [75]:
data.duplicated().sum()

np.int64(15)

In [76]:
data=data.drop(columns='id')

In [77]:
data=data.drop(columns='Unnamed: 32')

In [78]:
data.head()

,Diagnosis,Radius_Mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,SMOOTHNESS_WORST,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,B,13.28,13.72,85.79,541.8,0.08363,0.08575,0.05077,0.02864,0.1617,...,14.24,17.37,96.59,623.7,0.1166,0.2685,0.2866,0.09173,0.2736,0.07320
1,B,13.15,15.34,85.31,538.9,0.09384,0.08498,0.09293,0.03483,0.1822,...,14.77,20.50,97.67,677.3,0.1478,0.2256,0.3009,0.09722,0.3849,0.08633
2,b,15.19,13.21,97.65,711.8,0.07963,0.06934,NaN,0.02657,0.1721,...,16.20,15.73,104.50,819.1,0.1126,0.1737,0.1362,0.08178,0.2487,0.06766
3,b,11.34,21.26,72.48,396.5,0.08759,0.06575,0.05133,0.01899,0.1487,...,13.01,29.15,83.99,518.1,0.1699,0.2196,0.3120,0.08278,0.2829,0.08832
4,B,12.46,19.89,80.43,471.3,0.08451,0.10140,0.06830,0.03099,0.1781,...,13.46,23.07,88.13,551.3,0.1050,0.2158,0.1904,0.07625,0.2685,0.07764

**drop duplicates**

In [79]:
data=data.drop_duplicates().reset_index(drop=True)

In [80]:
data['Diagnosis']=data['Diagnosis'].astype(str).str.strip()
data['Diagnosis']=data['Diagnosis'].astype('category')

In [81]:
data.columns = data.columns.str.strip()

In [82]:
data['area_mean']=data['area_mean'].astype(str).str.extract(r'(-?\d+\.?\d*)')

data['area_mean']=pd.to_numeric(data['area_mean'],errors='coerce')

In [83]:
print(data['Diagnosis'].unique())

['B', 'b', 'benign', 'M', 'Benign', 'Malignant', 'malignant', 'm', 'nan']
Categories (9, object): ['B', 'Benign', 'M', 'Malignant', ..., 'benign', 'm', 'malignant', 'nan']

In [84]:
data['Diagnosis'] = data['Diagnosis'].astype(str).str.strip().str.lower()

data['Diagnosis'] = data['Diagnosis'].replace({
    'b': 0,
    'benign': 0,
    'm': 1,
    'malignant': 1,
    'nan': float(
        'nan'
    )
})

print(data['Diagnosis'].value_counts(dropna=False))

Diagnosis
0.0    357
1.0    211
NaN      4
Name: count, dtype: int64

/tmp/ipykernel_58/3313525475.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  data['Diagnosis'] = data['Diagnosis'].replace({

In [85]:
for col in data.columns:
    print(data[col].unique())

[ 0.  1. nan]
[  13.28    13.15    15.19    11.34    12.46    11.43    11.49     9.738
   16.17    16.35    15.13     9.683   19.53    16.27    12.43    13.68
   12.72  1427.      11.37    12.81    11.81    12.34    12.25    12.07
   15.46    12.87    18.77    10.17    11.8      9.787   15.66    11.76
   13.87    15.85    12.8     11.42    20.16     7.691   12.16    13.65
   14.06    11.66    10.2     12.32    18.94    12.23    11.14    13.75
   11.93     7.76     6.981   17.35    11.25    18.82    14.74    16.46
   18.63    14.42    11.52    18.22    13.66    12.27    12.04    18.49
   11.27    13.64    13.5     12.99    12.1     11.62    11.04    19.19
   13.94    11.71     9.742 1286.      16.3     13.46    14.92    11.54
   12.47    10.16    16.03     9.72    11.13     8.196   17.42    11.51
    9.668   16.6     15.49    25.22    11.29    21.16    11.22    19.4
   14.99    21.75    11.67    18.08    16.02    20.18    14.69    10.48
   17.02    15.34    17.14    11.68    12.75    10.32    16.24    16.11
   16.16    17.6     11.94    14.64    13.59    14.78    10.29    20.47
   19.55    11.08    12.77    23.21    11.3     13.44    14.02  1403.
   19.68    13.4     19.21    10.9      8.888   14.62    13.24    12.65
   12.83    20.34    11.16    11.46    11.41    11.74    14.29    10.49
    9.676   11.61    13.88    15.78    17.95    21.1     15.04    14.95
   11.9     14.44    10.96    10.65    19.59    11.89    17.75    17.46
    9.755   11.06    11.85    11.84    15.08    13.2     13.08    10.51
   16.26    17.99    18.81    13.47    13.56    12.18     9.268   19.69
   14.05    13.05    12.56     9.042 2029.      14.96    12.31    15.53
    8.571   12.62    11.45    12.2     14.58    14.04    12.54    20.13
   12.95    22.27    12.88    13.73    10.66    10.18     8.726   14.97
   23.09    12.       8.618   19.44    14.48    23.27    11.6     14.2
   17.47    19.16    10.95    12.06    12.86    20.92    15.3     15.73
   11.87    13.       9.465   14.9     23.29    15.75    12.85    14.71
   12.39    14.25    14.81    12.63    14.86    11.36    14.76    19.79
   13.21    19.8     13.37    13.9     15.22    10.82     9.876   13.34
   12.03    17.19    12.89    15.      15.61    13.98    17.3     13.43
   20.48    10.03    11.28    13.71    28.11    11.99    14.54    12.94
   13.03    16.25    13.77    16.14    13.8      9.436   12.05    14.68
   15.37    12.36    15.12    14.22    23.51    16.84    15.71    12.21
   14.6     19.81    10.97    13.38    14.11    17.93    19.89    14.61
    9.667   16.13    21.09    15.28    17.01    15.06    12.45    24.25
    8.598   11.5     13.85    10.94    18.31    11.75     8.878   11.31
   16.65    12.22    20.44    13.61    24.63    12.3     22.01    13.01
   10.26     7.729   16.69    14.47    13.17    13.45    12.78    10.91
 1175.      12.76    10.75    13.14    19.       9.333   20.09    17.85
    9.904   11.32    20.58    15.1     12.9     12.42    14.19    14.26
   11.7     19.45    13.78    17.68  1861.      10.6      8.597   12.68
   10.8     13.96    15.5     11.15    13.11    20.57     9.606   10.71
   20.73     9.847   12.4     17.27    21.71    20.26    14.59    25.73
   19.07    13.3      9.405   14.53     8.95    18.65    14.87    11.26
   18.05     9.397    9.173   10.05    12.49    17.05    14.8     14.45
   11.57    13.82    18.66    11.2      9.       9.423   16.5     18.46
   14.34    10.57    17.29    12.98    20.51    13.53    15.05    18.01
   19.02    15.7     13.49    20.59     9.567    9.295   21.37     9.777
   11.64    12.7     18.45    19.17    10.44    19.73    10.25    17.57
   27.22    15.27    21.56    13.74    19.18    20.64    12.58    17.06
   17.08    13.51    13.48    27.42    13.86    20.6     10.88    11.63
   20.31    16.74    11.33    21.61    13.62    13.81     9.504   12.96
   19.1     12.19    14.5     19.27    13.54    13.27     8.219   11.95
   13.69    17.91    15.32    17.2     12.91    13.7     13.16    10.86
   14.4     17.54    14.41     9.731   12.67    18.03    18.25    20.94
   16.07     8.734    9.029   16.78    20.2     20.55    10.08    11.47
   11.69     8.671]
[13.72 15.34 13.21 21.26 19.89 17.31 14.59 11.97 16.07 23.29 29.81 19.34
 18.9  20.71 17.   16.33 13.78 22.55 18.89 13.06 17.39 12.27 22.44 13.44
 11.89 19.54 21.43 14.88 16.58 19.94 23.2  21.6  16.21 23.95 17.46 20.38
 17.94 19.66 25.44 18.03 13.16 17.18   nan 17.48 12.39 21.31 19.56 14.07
 23.77 21.53 24.54 13.43 23.06 14.78 21.97 25.42 20.11 25.11 19.77 14.93
 14.95 18.7  19.13 17.92 28.14 17.52 15.5  16.34 12.71 14.23 17.72 18.18
 16.83 15.94 13.17 15.45 19.12 13.32 26.86 15.7  18.75 10.72 18.6  19.59
 15.51 18.22 16.62 16.84 25.56 23.93 18.1  28.08 19.97 24.91 13.04 23.04
 33.81 23.5  25.2  20.99 20.02 21.84 23.24 23.97 13.98 14.98 23.98 14.26
 16.4  16.17 16.7  16.35 18.77 18.05 21.54 23.33 18.24 15.24 17.84 23.94
 27.61 20.67 28.21 28.77 18.83 29.43 26.97 18.19 21.58 15.66 19.86 15.67
 21.25 21.68 18.57 12.96 14.64 24.02 20.13 18.17 22.33 21.51 17.19 15.6
 21.41 18.16 10.82 14.02 16.82 18.61 16.02 16.16 22.91 20.01 20.52 16.74
 17.57 14.65 15.18 17.62 25.22 18.15 14.44 18.35 28.03 39.28 28.2  14.96
 25.74 15.82 15.71 20.19 21.88 10.38 19.98 14.06 13.9  14.08 12.87 27.15
 19.31 14.34 19.1  29.97 16.52 33.56 13.1  20.97 15.21 15.98 18.07 13.66
 28.25 19.67 22.61 15.15 17.53 15.83 19.76 19.83 11.79 18.82 21.46 22.04
 12.84 20.53 24.68 26.6  21.35 24.49 14.71 18.   25.09 25.27 11.28 17.36
 20.78 21.01 20.7  16.54 22.53 26.67 19.22 21.37 21.59 22.15 14.7  20.76
 23.21 15.65 14.74 25.12 28.06 21.56 16.39 30.62 24.21 19.4  15.86 22.07
 19.38 19.62 17.08 19.63 21.28 13.39 18.68 10.91 18.47 12.83 24.89 27.54
 22.22 18.42 19.51 17.27 13.27 14.86 15.79 18.32 19.29 22.72 22.76 21.8
 16.68 27.85 24.27 17.43 19.46 13.93 18.02 17.2  30.72 12.88 24.48 17.67
 20.26 15.69 17.15 17.88 26.57 22.41 16.41 14.09 20.2  18.36 20.98 18.45
 17.21 20.66 18.59 18.58 25.   17.56 15.49 19.04 21.38 25.13 20.04 21.78
 24.69 19.02 21.9  12.22 25.49 20.25 24.99 18.3  16.49 21.72 12.35 20.18
 18.84 17.89 14.97 20.74 18.91 21.94 23.86 24.04 13.23 18.06 27.08 22.14
 15.92 15.04 20.83 23.81 19.11 19.33 16.85 21.82 18.95 23.84 21.98 17.05
 21.08 13.08 14.63 22.54 13.12 17.77 20.39 31.12 15.68 17.68 17.25 23.03
 22.68 24.81 21.57 21.7  15.76 17.6  17.12 16.67 19.96 16.15 13.86 23.09
 17.26 19.08 18.14 20.22 29.37 14.11 14.4  27.88 18.29 12.74 18.52 13.47
 22.13 19.35 27.81 10.94 19.07 20.56 24.59 25.25 20.31 15.56 19.6  22.3
 21.24 20.68 15.91 15.1  16.99 18.33 12.17 24.8  15.46 23.12 19.82 16.18
 15.05 16.95 24.98 12.91 22.47 15.73 22.39 17.91 22.49 17.35  9.71 14.69
 18.4  21.   22.11 19.48 20.82 16.94 26.27 16.93 20.21 20.28 22.02 29.33
 15.62 29.29 27.06 13.84 14.16 22.28 18.54 23.23 18.66 23.75 12.44 26.29
 13.29 21.17 10.89 26.47 20.58 14.36 32.47 19.24 17.02 14.76 18.87 21.02
 24.52 17.64 15.39 20.54 26.99 19.32 13.37 19.73 15.9  19.65 14.92 17.3
 21.81 23.56 17.33 18.8  28.92 26.83 20.86 14.83 15.11 16.03 18.94 16.32
 24.44 22.29 14.45]
[ 85.79  85.31  97.65  72.48  80.43  73.66  73.99  61.24 106.3  109.
  96.71  61.05 129.5  106.9   78.6   87.76  81.78  93.77  72.17  81.29
  75.27  78.94  78.18  77.83 102.5   82.67 122.9   64.55  78.99  62.11
 110.2   74.72  88.52 103.7   83.05  77.58  78.27 131.1   48.34  78.29
  87.88  89.75  73.7     nan  78.85 123.6   78.54  71.24  88.54  76.53
  47.92  43.79 111.    71.38 123.7   94.7  109.3  124.8   94.48  73.87
 120.3   89.46  78.41  76.85 121.3   73.38  87.21  85.69  84.08  78.07
  76.38  70.92 126.3   90.31  75.03  61.93  82.82  81.15 104.7   87.44
  73.34  96.45  73.73  81.09  64.73 105.8   60.73  70.47  51.71 114.5
  74.52  61.06 108.3  102.4  171.5   72.23 137.2   70.79 129.1   95.54
 147.3   75.21 117.4  102.7  143.7   98.22  67.49 112.8   71.49 116.
  75.49  82.51  65.31 108.8  106.2  119.    75.71  95.77  86.24  97.4
  65.67 134.7   85.89 133.6   73.3   81.35 153.5   73.93  86.18  89.59
  66.72  61.5   89.79 129.9   85.48 125.5   68.69  58.79  94.57  86.87
  82.69  85.26 135.9   74.68  87.38  70.95  73.59  74.24  90.3   66.86
  64.12  75.46 105.7  114.2  138.1   98.73  96.85  78.11  93.97  68.01
 130.7   74.65  77.32 117.3  113.4   61.68  75.54  77.93  98.    84.07
  85.63  68.64 107.5  122.8  120.9   70.67  87.32  88.59  77.25  61.49
 130.    91.38  82.61  81.92  60.07 135.1   97.03  77.42  79.19  82.02
  54.53  73.81  78.01  97.41  89.78  79.42  94.29 131.2   83.14 152.8
  84.45  97.84  93.6   65.12  55.84  95.5  152.1   76.77  54.34 128.1
  94.25  74.34  92.41 116.1  126.2   71.9   76.66  74.23  70.21  83.19
 143.   102.8   76.2   76.83  83.51  60.11  89.77  94.15 102.1  158.9
 107.1   82.63  95.55  80.64  96.42  94.66  80.45  82.15 100.4   76.95
  72.49 103.8   94.87 130.4   84.88 129.7   77.79  86.1   88.97 103.4
  68.89  63.95  86.49  76.09 111.6   97.45  73.16 100.    91.12 113.
  85.84 132.5   63.19  73.    87.16  88.73  76.14 188.5   78.83  77.61
  96.73  79.85  83.18  88.27 109.8   62.92  88.06 104.3   90.43  59.82
  67.41  78.75  94.74 100.2   79.78  98.78  77.22  92.55 155.1   84.13
 108.4  102.    78.31  71.73  86.34  90.03 115.2   80.98 130.5   92.68
  80.62  82.38 142.7   98.92 109.7  100.3   82.85  78.78 166.2   73.88
  54.66  73.28  88.44 117.8   70.39 118.6  127.7   75.89  56.74  71.8
 110.    79.47 133.8  165.5   77.88 147.2   82.01  65.75  47.98 102.6
  95.81  84.28  86.6   81.37  93.63  69.14  76.1   81.87 103.6   68.26
  85.98 123.4   59.01  83.97 114.6   64.6   71.76  99.58  83.74  78.61
  90.2   92.87  91.22  74.33 126.5   94.21  88.37  87.5  122.1   69.28
  54.09  68.79  91.43 102.9   70.87  78.04  87.02  81.89 132.9   61.64
  69.5  135.7   63.    81.47 140.9  132.4   96.39 174.2  128.3   59.6
  93.86  58.74  71.25  98.64  73.72 120.2   72.76 128.9   65.85  59.75
  59.2   64.41  66.85  75.26  75.    95.88  94.49  74.2   92.33 121.4
  84.95  56.36  59.26 106.6   76.84 121.1   92.51  70.15 114.4   84.52
 134.4   87.91  97.26 118.4  122.    84.1  101.2   71.94  88.68  86.91
 137.8   82.57 108.1   60.21  59.96 141.3   62.5   75.17  66.82  80.88
  66.62  94.37  66.52 127.2  115.    96.22 182.1   88.05  98.17  81.72
  82.89 142.    88.12 127.5  134.8   68.77  76.31  79.83 111.8  111.2
  88.1   97.53 101.7   88.4   94.89 186.9   90.96  96.12 140.1   70.41
  74.87 110.1   82.71  71.79 144.4   79.01  87.19  91.56  60.34  84.18
  79.08  76.39  77.87  94.28 127.9  120.8   87.46 128.    85.09  84.55
  84.74 118.7   71.3   88.99  77.23  87.84 124.4  103.2   82.53  73.06
  84.06  68.51  92.25 115.1   82.29  96.03  97.83  73.53  63.78  81.25
  85.42 117.5  119.6  138.9  104.1   88.64  55.27  82.5  133.7   66.2
  70.31  63.76  73.02  75.51  76.37  90.63  54.42]
[5.418e+02 5.389e+02 7.118e+02 3.965e+02 4.713e+02 3.980e+02 4.049e+02
 2.885e+02 7.885e+02 8.404e+02 7.195e+02 2.857e+02 1.217e+03 8.137e+02
 4.773e+02 5.755e+02 4.921e+02 6.298e+02 3.960e+02 5.088e+02 4.289e+02
 4.685e+02 4.665e+02 4.452e+02 7.369e+02 5.092e+02 1.092e+03 3.119e+02
 4.320e+02 2.945e+02 7.735e+02 4.279e+02 5.937e+02 7.827e+02 5.083e+02
 3.861e+02 4.603e+02 1.274e+03 1.704e+02 4.553e+02 5.689e+02 6.091e+02
 4.210e+02 3.212e+02 4.641e+02 1.130e+03 4.610e+02 3.846e+02 5.900e+02
 4.386e+02 1.810e+02 1.435e+02 9.331e+02 3.900e+02 1.110e+03 6.686e+02
 8.329e+02 1.088e+03 6.425e+02 4.063e+02 4.691e+02 1.033e+03 5.753e+02
 4.661e+02 4.499e+02 1.068e+03 3.920e+02 5.718e+02 5.662e+02 5.143e+02
 4.462e+02 4.088e+02       nan 1.157e+03 5.942e+02 4.203e+02 2.897e+02
 5.048e+02 4.774e+02 8.198e+02 5.511e+02 4.090e+02 6.869e+02 4.091e+02
 4.819e+02 3.117e+02 7.932e+02 2.881e+02 3.811e+02 2.019e+02 9.480e+02
 4.035e+02 2.863e+02 8.581e+02 7.447e+02 1.878e+03 3.880e+02 1.000e+00
 3.868e+02 1.155e+03 6.988e+02 1.491e+03 1.024e+03 7.978e+02 1.245e+03
 6.561e+02 3.336e+02 8.993e+02 7.044e+02 3.784e+02 9.127e+02 4.205e+02
 4.938e+02 3.249e+02 8.051e+02 8.130e+02 8.098e+02 9.805e+02 4.376e+02
 6.519e+02 5.723e+02 6.683e+02 3.214e+02 1.299e+03 5.621e+02 3.616e+02
 5.079e+02 3.894e+02 5.630e+02 6.065e+02 3.377e+02 2.899e+02 6.034e+02
 1.194e+03 5.524e+02 3.668e+02 2.440e+02 6.627e+02 5.429e+02 4.856e+02
 5.032e+02 1.264e+03 3.803e+02 4.031e+02 4.033e+02 4.273e+02 6.326e+02
 3.343e+02 2.725e+02 4.082e+02 5.966e+02 7.826e+02 9.820e+02 1.384e+03
 6.894e+02 6.781e+02 4.328e+02 6.401e+02 3.656e+02 3.470e+02 1.214e+03
 4.029e+02 4.322e+02 9.816e+02 9.206e+02 2.909e+02 3.739e+02 4.327e+02
 4.406e+02 7.166e+02 5.373e+02 5.200e+02 3.342e+02 8.268e+02 1.102e+03
 3.727e+02 5.463e+02 5.613e+02 4.614e+02 2.487e+02 1.203e+03 6.004e+02
 5.272e+02 4.858e+02 2.445e+02 1.297e+03 6.873e+02 4.654e+02 4.709e+02
 5.074e+02 7.449e+02 2.213e+02 4.964e+02 4.015e+02 4.579e+02 6.448e+02
 6.112e+02 4.919e+02 6.588e+02 5.137e+02 1.509e+03 4.931e+02 6.895e+02
 5.783e+02 3.496e+02 3.131e+02 2.309e+02 6.902e+02 1.682e+03 4.425e+02
 2.245e+02 1.167e+03 6.482e+02 1.686e+03 4.126e+02 6.184e+02 9.846e+02
 1.138e+03 3.711e+02 4.453e+02 4.172e+02 5.063e+02 1.347e+03 7.324e+02
 7.472e+02 4.356e+02 5.194e+02 2.694e+02 5.848e+02 6.412e+02 6.850e+02
 1.685e+03 7.586e+02 5.145e+02 6.569e+02 4.629e+02 6.457e+02 6.807e+02
 4.801e+02 4.804e+02 6.714e+02 4.433e+02 3.998e+02 7.313e+02 6.687e+02
 1.192e+03 5.384e+02 1.230e+03 4.511e+02 5.535e+02 5.994e+02 7.169e+02
 2.983e+02 4.460e+02 9.283e+02 5.166e+02 6.845e+02 3.863e+02 5.995e+02
 9.282e+02 5.654e+02 1.306e+03 3.073e+02 3.848e+02 5.610e+02 5.710e+02
 4.427e+02 2.499e+03 4.413e+02 4.645e+02 5.076e+02 5.806e+02 5.238e+02
 8.158e+02 2.954e+02 5.827e+02 8.000e+02 2.786e+02 3.361e+02 4.478e+02
 7.282e+02 4.587e+02 6.239e+02 1.747e+03 5.416e+02 8.802e+02 7.617e+02
 4.584e+02 6.647e+02 3.715e+02 5.572e+02 6.165e+02 9.989e+02 5.013e+02
 2.891e+02 4.929e+02 5.122e+02 8.072e+02 1.311e+03 7.106e+02 9.043e+02
 7.056e+02 4.767e+02 4.620e+02 1.761e+03 4.127e+02 2.218e+02 4.074e+02
 5.887e+02 9.917e+02 3.700e+02 1.041e+03 1.191e+03 4.229e+02 2.410e+02
 3.941e+02 9.046e+02 5.202e+02 4.531e+02 1.293e+03 5.726e+02 4.644e+02
 1.482e+03 5.264e+02 3.216e+02 1.788e+02 8.576e+02 7.613e+02 6.564e+02
 5.551e+02 5.025e+02 6.330e+02 3.637e+02 4.198e+02 4.966e+02 7.810e+02
 3.553e+02 5.369e+02 2.640e+02 4.759e+02 9.921e+02 3.024e+02 3.957e+02
 1.290e+03 6.745e+02 4.765e+02 5.779e+02 6.107e+02 6.331e+02 4.187e+02
 1.169e+03 6.660e+02 5.859e+02 5.198e+02 9.637e+02 1.094e+03 3.464e+02
 2.212e+02 4.990e+02 3.599e+02 6.024e+02 8.031e+02 3.819e+02 4.493e+02
 5.294e+02 5.159e+02 1.326e+03 2.805e+02 3.449e+02 2.932e+02 4.678e+02
 9.288e+02 1.546e+03 6.571e+02 2.010e+03 5.461e+02 2.712e+02 6.442e+02
 2.452e+02 1.076e+03 3.665e+02 6.825e+02 1.006e+03 3.912e+02 3.208e+02
 2.688e+02 2.609e+02 3.108e+02 4.816e+02 4.319e+02 8.950e+02 4.311e+02
 6.748e+02 6.427e+02 4.097e+02 5.959e+02 1.077e+03 3.860e+02 2.463e+02
 2.713e+02 8.381e+02 4.486e+02 1.075e+03 3.383e+02 9.478e+02 5.140e+02
 5.592e+02 7.019e+02 1.007e+03 5.379e+02 7.666e+02 5.302e+02 3.873e+02
 5.926e+02 1.320e+03 4.771e+02 7.988e+02 2.796e+02 2.578e+02 2.902e+02
 4.125e+02 3.409e+02 4.950e+02 1.123e+03 3.296e+02 6.099e+02 3.242e+02
 1.145e+03 9.551e+02 6.859e+02 2.250e+03 7.255e+02 5.069e+02 5.850e+02
 1.148e+03 1.335e+03 3.576e+02 4.260e+02 4.236e+02 4.890e+02 9.186e+02
 9.309e+02 5.581e+02 6.937e+02 7.489e+02 6.737e+02 2.501e+03 5.789e+02
 6.809e+02 5.452e+02 7.128e+02 1.265e+03 3.589e+02 4.151e+02 1.288e+03
 8.695e+02 5.306e+02 3.966e+02 4.667e+02 5.732e+02 5.346e+02 5.978e+02
 2.739e+02 5.252e+02 4.558e+02 4.338e+02 4.410e+02 6.407e+02 1.162e+03
 1.052e+03 5.663e+02 1.223e+03 6.029e+02 5.120e+02 5.464e+02 5.517e+02
 2.039e+02 6.597e+02 3.881e+02 5.874e+02 4.267e+02 5.791e+02 9.940e+02
 7.133e+02 9.294e+02 5.164e+02 5.711e+02 5.387e+02 3.605e+02 6.461e+02
 9.516e+02 5.041e+02 6.510e+02 4.637e+02 6.299e+02 4.020e+02 3.002e+02
 4.899e+02 5.315e+02 9.900e+02 1.364e+03 8.177e+02 5.567e+02 2.343e+02
 1.250e+03 2.505e+02 8.863e+02 1.234e+03 1.308e+03 3.782e+02 3.175e+02
 4.027e+02 4.280e+02 4.763e+02 5.889e+02 2.272e+02]
[0.08363 0.09384 0.07963 0.08759 0.08451 0.1092  0.1046  0.0925  0.0988
 0.09742 0.0832  0.08491 0.115   0.1169  0.07557 0.09277 0.09667 0.1038
 0.08713 0.08739 0.1007  0.09003 0.08192 0.11    0.1257  0.09136 0.09116
 0.1134  0.1091  0.1024  0.1109  0.08637 0.08743 0.08401 0.08044 0.1425
 0.08654 0.0802  0.08668 0.09087 0.09646 0.08045 0.07561 0.08054 0.1028
 0.09009 0.09586 0.07274 0.08043 0.09768 0.05263 0.117   0.08662 0.08306
 0.1018  0.08275 0.09831 0.1064  0.09752 0.1013  0.08682 0.1148  0.09057
 0.08685 0.08752 0.1012  0.08365 0.07685 0.07376 0.09462 0.1029  0.1175
 0.1077  0.08694 0.1248  0.1075  0.1034  0.09427 0.09524 0.08098 0.08597
 0.09965 0.1003  0.09491 0.0695  0.08151 0.086   0.1006  0.09261 0.08311
 0.08455 0.116   0.1063  0.09834 0.09428 0.0778  0.1027  0.09387 0.09401
 0.1016  0.07371 0.08206 0.1286  0.1031  0.09816 0.1197  0.1073  0.09566
 0.1186  0.1128  0.1125  0.09434 0.1066  0.09721 0.1008  0.09289 0.08261
 0.1132  0.07948 0.1172  0.0903  0.09156 0.07517 0.0926  0.1216  0.08276
 0.09509 0.09592 0.08162 0.07966 0.107   0.09037 0.0907  0.09797 0.07937
 0.1053  0.07515 0.09783 0.08974 0.08284 0.1076  0.1088  0.09774 0.09423
 0.08853 0.09373 0.07813 0.06429 0.1068  0.1255  0.07026 0.1155  0.08402
 0.09684 0.09883 0.1167  0.1152  0.0997  0.09687 0.09657 0.112   0.09984
 0.09363 0.09997 0.09812 0.07984 0.1033  0.08372 0.08511 0.1122  0.1165
 0.1184  0.08923 0.07987 0.1071  0.1051  0.07734 0.1634  0.1096  0.09929
 0.0806  0.0876  0.09968 0.08992 0.07699 0.09172 0.08749 0.1036  0.07903
 0.1102  0.08673 0.1054  0.08458 0.07436 0.09832 0.0978  0.1005  0.1326
 0.1218  0.08138 0.1131  0.08792 0.1061  0.08421 0.09342 0.08437 0.1089
 0.09444 0.08439 0.08983 0.08931 0.1049  0.102   0.1227  0.08386 0.07474
 0.09934 0.1099  0.1082  0.1043  0.1225  0.06613 0.1135  0.1044  0.09578
 0.09751 0.09947 0.1141  0.1243  0.07551 0.1137  0.1042  0.08472 0.08928
 0.09933 0.09723 0.08858 0.1183  0.08875 0.1015  0.08671 0.09383 0.1045
 0.07115 0.06828 0.1048  0.1078  0.07683 0.09726     nan 0.08371 0.1237
 0.0784  0.106   0.09048 0.08355 0.08117 0.1164  0.07956 0.09916 0.08872
 0.1142  0.07372 0.103   0.1139  0.09879 0.08268 0.1026  0.09198 0.09495
 0.1009  0.09989 0.06935 0.09867 0.092   0.08772 0.08876 0.08013 0.08223
 0.1069  0.07445 0.09231 0.08915 0.09245 0.09309 0.08855 0.07896 0.1037
 0.07618 0.08946 0.08583 0.09425 0.104   0.1039  0.09514 0.08108 0.1447
 0.08508 0.09345 0.08785 0.1004  0.08588 0.1032  0.08293 0.08139 0.1121
 0.08369 0.0915  0.09258 0.08313 0.06251 0.09996 0.07497 0.1025  0.08837
 0.07466 0.1022  0.09823 0.08518 0.09676 0.0971  0.07793 0.08675 0.08217
 0.0924  0.108   0.07838 0.09699 0.06883 0.0909  0.08677 0.07926 0.1189
 0.09463 0.06576 0.08814 0.1035  0.08641 0.08817 0.1273  0.1115  0.0944
 0.09688 0.1074  0.08801 0.09754 0.1002  0.06955 0.08474 0.08481 0.09469
 0.09492 0.08331 0.09078 0.08473 0.1149  0.09081 0.08582 0.1194  0.1162
 0.1065  0.101   0.08877 0.07969 0.07721 0.09179 0.09872 0.08546 0.07449
 0.07005 0.08123 0.09686 0.09311 0.09874 0.09906 0.09073 0.08999 0.09579
 0.09159 0.1291  0.09215 0.1001  0.09029 0.08791 0.09597 0.1398  0.08684
 0.1085  0.1278  0.08464 0.1371  0.08142 0.0943  0.0974  0.1062  0.09847
 0.09855 0.1094  0.09488 0.08182 0.09055 0.0904  0.111   0.07944 0.08523
 0.09446 0.09594 0.08099 0.08393 0.1119  0.09898 0.1059  0.08515 0.08924
 0.1084  0.09587 0.1041  0.09056 0.1178  0.09357 0.1     0.0961  0.08352
 0.09379 0.08477 0.09246 0.1158  0.1323  0.07351 0.1215  0.09773 0.08605
 0.1101  0.09779 0.0842  0.07991 0.08445 0.07355 0.09405 0.09746 0.08388
 0.09516 0.08302 0.123   0.1335  0.07941 0.0995  0.09639 0.07335 0.07431
 0.06995 0.08968 0.08794 0.08757 0.0808  0.07837 0.09059 0.1072  0.09714
 0.08947 0.09168 0.1106  0.1133  0.08865 0.09905 0.09882 0.07741 0.09076
 0.08871 0.1236  0.12    0.09138]
[ 0.08575  0.08498  0.06934  0.06575  0.1014   0.09486  0.08228  0.04102
  0.1438   0.1497   0.04605  0.0503   0.1642   0.1319   0.03454  0.07255
  0.08393  0.1154   0.05008  0.03774  0.05562  0.06307  0.052    0.09009
  0.1555   0.07883  0.1402   0.08061  0.17     0.05301  0.3114   0.04966

In [86]:
mode_diagnosis=data['Diagnosis'].mode()[0]
data['Diagnosis']=data['Diagnosis'].fillna(mode_diagnosis)
data['Diagnosis'].isna().sum()

np.int64(0)

In [87]:
num_cols=data.select_dtypes(include=['float64','float32','int32','int64']).columns

for col in num_cols:
    q1=data[col].quantile(0.25)
    q3=data[col].quantile(0.75)
    iqr=q3-q1
    upper_bound=q3+(iqr*1.5)
    lower_bound=q1-(iqr*1.5)
    data[col]=np.clip(data[col],lower_bound,upper_bound)

imputer=KNNImputer(n_neighbors=5)

if(len(num_cols))>0:
    data[num_cols]=imputer.fit_transform(data[num_cols])

In [88]:
data.isna().sum()

Diagnosis                  0
Radius_Mean                0
texture_mean               0
perimeter_mean             0
area_mean                  0
smoothness_mean            0
compactness_mean           0
concavity_mean             0
concave points_mean        0
symmetry_mean              0
fractal_dimension_mean     0
radius_se                  0
texture_se                 0
perimeter_se               0
area_se                    0
smoothness_se              0
compactness_se             0
concavity_se               0
concave points_se          0
symmetry_se                0
fractal_dimension_se       0
radius_worst               0
texture_worst              0
perimeter_worst            0
area_worst                 0
SMOOTHNESS_WORST           0
compactness_worst          0
concavity_worst            0
concave points_worst       0
symmetry_worst             0
fractal_dimension_worst    0
dtype: int64

In [89]:
data.dtypes

Diagnosis                  float64
Radius_Mean                float64
texture_mean               float64
perimeter_mean             float64
area_mean                  float64
smoothness_mean            float64
compactness_mean           float64
concavity_mean             float64
concave points_mean        float64
symmetry_mean              float64
fractal_dimension_mean     float64
radius_se                  float64
texture_se                 float64
perimeter_se               float64
area_se                    float64
smoothness_se              float64
compactness_se             float64
concavity_se               float64
concave points_se          float64
symmetry_se                float64
fractal_dimension_se       float64
radius_worst               float64
texture_worst              float64
perimeter_worst            float64
area_worst                 float64
SMOOTHNESS_WORST           float64
compactness_worst          float64
concavity_worst            float64
concave points_worst       float64
symmetry_worst             float64
fractal_dimension_worst    float64
dtype: object

In [90]:
data.duplicated().sum()

np.int64(3)

In [91]:
data=data.drop_duplicates().reset_index(drop=True)

In [92]:
data.duplicated().sum()

np.int64(0)

In [93]:
X=data.drop(columns='Diagnosis')

y=data['Diagnosis']

In [94]:
x_train_val,x_test,y_train_val,y_test=train_test_split(X,y,stratify=y,test_size=0.2,random_state=42)

In [95]:
x_train,x_val,y_train,y_val=train_test_split(x_train_val,y_train_val,stratify=y_train_val,random_state=42,test_size=0.25)

In [102]:
scaler=StandardScaler()

x_train_scaled=scaler.fit_transform(x_train)
x_val_scaled=scaler.transform(x_val)
x_test_scaled=scaler.transform(x_test)

**Buld the model**

In [97]:
model=tf.keras.Sequential([
    layers.Input(shape=(30,)),
    layers.Dense(32,activation='relu'),
    layers.Dense(13,activation='relu'),
    layers.Dense(1,activation='sigmoid')
])

In [98]:
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['recall']
)

In [99]:
early_stop=EarlyStopping(
    monitor='val_loss',
    patience=5,
    restore_best_weights=True
)

In [103]:
history=model.fit(
    x_train_scaled,
    y_train,
    epochs=100,
    validation_data=(x_val_scaled,y_val),
    verbose=1,
    batch_size=32,
    callbacks=[early_stop]
)

Epoch 1/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 2s 30ms/step - loss: 0.6087 - recall: 0.5280 - val_loss: 0.4700 - val_recall: 0.8095
Epoch 2/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.4485 - recall: 0.7840 - val_loss: 0.3466 - val_recall: 0.9048
Epoch 3/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.3480 - recall: 0.8480 - val_loss: 0.2627 - val_recall: 0.9286
Epoch 4/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2765 - recall: 0.8720 - val_loss: 0.2124 - val_recall: 0.9286
Epoch 5/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2322 - recall: 0.8800 - val_loss: 0.1800 - val_recall: 0.9286
Epoch 6/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.2021 - recall: 0.9040 - val_loss: 0.1610 - val_recall: 0.9524
Epoch 7/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1815 - recall: 0.9040 - val_loss: 0.1483 - val_recall: 0.9524
Epoch 8/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1672 - recall: 0.9200 - val_loss: 0.1396 - val_recall: 0.9524
Epoch 9/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1574 - recall: 0.9280 - val_loss: 0.1324 - val_recall: 0.9524
Epoch 10/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1487 - recall: 0.9280 - val_loss: 0.1276 - val_recall: 0.9524
Epoch 11/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1428 - recall: 0.9440 - val_loss: 0.1235 - val_recall: 0.9524
Epoch 12/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1374 - recall: 0.9440 - val_loss: 0.1200 - val_recall: 0.9524
Epoch 13/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1313 - recall: 0.9440 - val_loss: 0.1181 - val_recall: 0.9524
Epoch 14/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1272 - recall: 0.9440 - val_loss: 0.1163 - val_recall: 0.9524
Epoch 15/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1232 - recall: 0.9520 - val_loss: 0.1145 - val_recall: 0.9524
Epoch 16/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 0.1195 - recall: 0.9680 - val_loss: 0.1133 - val_recall: 0.9524
Epoch 17/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1160 - recall: 0.9680 - val_loss: 0.1124 - val_recall: 0.9524
Epoch 18/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1126 - recall: 0.9680 - val_loss: 0.1118 - val_recall: 0.9524
Epoch 19/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1096 - recall: 0.9680 - val_loss: 0.1107 - val_recall: 0.9524
Epoch 20/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1072 - recall: 0.9680 - val_loss: 0.1106 - val_recall: 0.9524
Epoch 21/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1039 - recall: 0.9760 - val_loss: 0.1101 - val_recall: 0.9524
Epoch 22/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.1010 - recall: 0.9760 - val_loss: 0.1095 - val_recall: 0.9762
Epoch 23/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0984 - recall: 0.9760 - val_loss: 0.1090 - val_recall: 0.9762
Epoch 24/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0960 - recall: 0.9760 - val_loss: 0.1091 - val_recall: 0.9762
Epoch 25/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0937 - recall: 0.9760 - val_loss: 0.1091 - val_recall: 0.9762
Epoch 26/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0914 - recall: 0.9760 - val_loss: 0.1096 - val_recall: 0.9762
Epoch 27/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0894 - recall: 0.9760 - val_loss: 0.1101 - val_recall: 0.9762
Epoch 28/100
11/11 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0870 - recall: 0.9760 - val_loss: 0.1103 - val_recall: 0.9762

In [104]:
test_loss, test_recall = model.evaluate(x_test_scaled, y_test)

print(f'Test Loss: {test_loss:.4f}')
print(f'Test Recall: {test_recall:.4f}')

4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - loss: 0.0680 - recall: 0.9762
Test Loss: 0.0680
Test Recall: 0.9762

In [105]:
model.save('breast_cancer_model.keras')